name: Deploy to EC2 (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/welive-app/nb01-welive-team2
            git pull origin main
            npm install
            npx prisma migrate deploy
            npm run build
            npx tsc-alias -p tsconfig.json
            pm2 delete welive-server || true
            pm2 start ecosystem.config.js
            pm2 save
